export const mockIngredients = [
  {
    name: 'แป้งเค้ก',
    purchaseUnit: 'กรัม',
    purchaseQuantity: 1000,
    purchasePrice: 45,
    costPerGram: 0.045,
    id: 1,
  },
  {
    name: 'น้ำตาลไอซิ่ง',
    purchaseUnit: 'กรัม',
    purchaseQuantity: 900,
    purchasePrice: 50,
    costPerGram: 0.0555,
    id: 2,
  },
  {
    name: 'เนยสดชนิดจืด',
    purchaseUnit: 'กรัม',
    purchaseQuantity: 227,
    purchasePrice: 120,
    costPerGram: 0.5286,
    id: 3,
  },
  {
    name: 'ไข่ไก่ (เบอร์ 1)',
    purchaseUnit: 'ฟอง',
    purchaseQuantity: 30,
    purchasePrice: 130,
    costPerGram: 0.07222222222222222,
    id: 4,
    defaultYield: 100,
    costByWholeUnit: true,
    standardWeightInGrams: 60,
  },
  {
    name: 'นมสดรสจืด',
    purchaseUnit: 'กรัม',
    purchaseQuantity: 800,
    purchasePrice: 50,
    costPerGram: 0.0625,
    id: 5,
  },
  {
    name: 'ผงโกโก้',
    purchaseUnit: 'กรัม',
    purchaseQuantity: 200,
    purchasePrice: 85,
    costPerGram: 0.425,
    id: 6,
  },
  {
    name: 'ดาร์กช็อกโกแลต 70%',
    purchaseUnit: 'กรัม',
    purchaseQuantity: 500,
    purchasePrice: 350,
    costPerGram: 0.7,
    id: 7,
  },
  {
    name: 'กลิ่นวานิลลา',
    purchaseUnit: 'ขวด',
    purchaseQuantity: 1,
    purchasePrice: 80,
    costPerGram: 0.8,
    id: 8,
    defaultYield: '',
    standardWeightInGrams: 100,
  },
  {
    name: 'นมผงฮอกไกโด',
    purchaseUnit: 'กรัม',
    purchaseQuantity: 480,
    purchasePrice: 140,
    costPerGram: 0.2916666666666667,
    id: 10,
  },
  {
    name: 'ยีสต์',
    purchaseUnit: 'กรัม',
    purchaseQuantity: 500,
    purchasePrice: 140,
    costPerGram: 0.28,
    id: 11,
  },
  {
    name: 'เกลือ',
    purchaseUnit: 'กรัม',
    purchaseQuantity: 1000,
    purchasePrice: 30,
    costPerGram: 0.03,
    id: 12,
  },
  {
    name: 'วิป',
    purchaseUnit: 'กรัม',
    purchaseQuantity: 1000,
    purchasePrice: 240,
    costPerGram: 0.24,
    id: 13,
  },
  {
    name: 'เนยจืด',
    purchaseUnit: 'กรัม',
    purchaseQuantity: 5000,
    purchasePrice: 1600,
    costPerGram: 0.32,
    id: 14,
  },
  {
    name: 'น้ำร้อน',
    purchaseUnit: 'กรัม',
    purchaseQuantity: 600,
    purchasePrice: 5,
    costPerGram: 0.008333333333333333,
    id: 15,
  },
  {
    name: 'น้ำตาล',
    purchaseUnit: 'กรัม',
    purchaseQuantity: 1000,
    purchasePrice: 31,
    costPerGram: 0.031,
    id: 16,
  },
  {
    name: 'น้ำมันพืช',
    purchaseUnit: 'ลิตร',
    purchaseQuantity: 1,
    purchasePrice: 60,
    costPerGram: 0.06315789473684211,
    id: 17,
  },
  {
    name: 'แป้งขนมปัง',
    purchaseUnit: 'กรัม',
    purchaseQuantity: 1000,
    purchasePrice: 40,
    defaultYield: 100,
    costPerGram: 0.04,
    id: 28,
  },
  {
    name: 'กล้วยหอม',
    purchaseUnit: 'ลูก',
    purchaseQuantity: 9,
    purchasePrice: 100,
    defaultYield: '',
    standardWeightInGrams: 80,
    costPerGram: 0.1388888888888889,
    id: 29,
  },
];

export const mockRecipes = [
  {
    name: 'ขนมปังไส้คัสตาร์ด (ตัวอย่าง)',
    isSubRecipe: false,
    ingredientsList: [
      {
        itemType: 'ingredient',
        itemId: 28,
        quantity: 150,
        yield: 100,
        costByWholeUnit: false,
      },
      {
        itemType: 'ingredient',
        itemId: 16,
        quantity: 20,
        yield: 100,
        costByWholeUnit: false,
      },
      {
        itemType: 'ingredient',
        itemId: 11,
        quantity: 2,
        yield: 100,
        costByWholeUnit: false,
      },
      {
        itemType: 'ingredient',
        itemId: 12,
        quantity: 2,
        yield: 100,
        costByWholeUnit: false,
      },
      {
        itemType: 'ingredient',
        itemId: 5,
        quantity: 30,
        yield: 100,
        costByWholeUnit: false,
      },
      {
        itemType: 'ingredient',
        itemId: 4,
        quantity: 20,
        yield: 100,
        costByWholeUnit: true,
      },
      {
        itemType: 'ingredient',
        itemId: 14,
        quantity: 20,
        yield: 100,
        costByWholeUnit: false,
      },
      {
        itemType: 'recipe',
        itemId: 3,
        quantity: 100,
        yield: 100,
        costByWholeUnit: false,
      },
    ],
    notes: '',
    id: 2,
  },
  {
    name: 'ไส้คัสตาร์ด (ตัวอย่าง)',
    isSubRecipe: true,
    ingredientsList: [
      {
        itemType: 'ingredient',
        itemId: 4,
        quantity: 58,
        yield: 100,
        costByWholeUnit: true,
      },
      {
        itemType: 'ingredient',
        itemId: 16,
        quantity: 40,
        yield: 100,
        costByWholeUnit: false,
      },
      {
        itemType: 'ingredient',
        itemId: 8,
        quantity: 3,
        yield: 100,
        costByWholeUnit: false,
      },
      {
        itemType: 'ingredient',
        itemId: 5,
        quantity: 20,
        yield: 100,
        costByWholeUnit: false,
      },
    ],
    notes: '',
    id: 3,
  },
  {
    name: 'เค้กกล้วยหอม (ตัวอย่าง)',
    isSubRecipe: false,
    ingredientsList: [
      {
        itemType: 'ingredient',
        itemId: 1,
        quantity: 200,
        yield: 100,
        costByWholeUnit: false,
      },
      {
        itemType: 'ingredient',
        itemId: 4,
        quantity: 130,
        yield: 100,
        costByWholeUnit: true,
      },
      {
        itemType: 'ingredient',
        itemId: 16,
        quantity: 40,
        yield: 100,
        costByWholeUnit: false,
      },
      {
        itemType: 'ingredient',
        itemId: 12,
        quantity: 5,
        yield: 100,
        costByWholeUnit: false,
      },
    ],
    notes: '',
    id: 4,
  },
];
